In [1]:
import sklearn
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('dadostreino.csv')

In [3]:
df

,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,dload,...,state_CON,state_ECO,state_FIN,state_INT,state_PAR,state_REQ,state_RST,state_URN,state_no,label
0,0.121478,6,4,258,172,74.087490,252,254,1.415894e+04,8.495365e+03,...,False,False,True,False,False,False,False,False,False,0
1,0.649902,14,38,734,42014,78.473372,62,252,8.395112e+03,5.035713e+05,...,False,False,True,False,False,False,False,False,False,0
2,1.623129,8,16,364,13186,14.170161,62,252,1.572272e+03,6.092923e+04,...,False,False,True,False,False,False,False,False,False,0
3,1.681642,12,12,628,770,13.677108,62,252,2.740179e+03,3.358622e+03,...,False,False,True,False,False,False,False,False,False,0
4,0.449454,10,6,534,268,33.373826,254,252,8.561499e+03,3.987060e+03,...,False,False,True,False,False,False,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238677,0.001117,2,2,146,178,2685.765426,31,29,5.228290e+05,6.374217e+05,...,True,False,False,False,False,False,False,False,False,0
238678,0.258123,20,23,2975,5188,237.882540,31,29,7.963140e+04,5.262271e+05,...,False,False,True,False,False,False,False,False,False,0
238679,0.031963,72,74,4276,64648,4582.379378,31,29,1.055827e+06,1.595650e+07,...,False,False,True,False,False,False,False,False,False,0
238680,0.000954,2,2,130,162,3144.268668,31,29,5.470169e+05,6.811724e+05,...,True,False,False,False,False,False,False,False,False,0
238681,0.006298,4,4,561,309,1111.527511,31,29,5.348308e+05,2.951461e+05,...,True,False,False,False,False,False,False,False,False,0

In [4]:
#%pip install pycaret

In [6]:
from pycaret.classification import *
classification = setup(
    session_id=6698,
    data=df,
    target='label',
    train_size=0.7,
    preprocess=False,
    use_gpu=False,
)

In [7]:
top3 = compare_models(n_select=3)

In [8]:
print(top3)

[RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=6698, verbose=0,
                       warm_start=False), ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=6698, verbose=0,
                     warm_start=False), LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=6698, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)]

In [9]:
melhores_modelos = top3[:3]

In [10]:
modelo1 = melhores_modelos[0]

In [11]:
print(modelo1)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=6698, verbose=0,
                       warm_start=False)

In [12]:
evaluate_model(modelo1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [13]:
teste = pd.read_csv('dadostreino.csv')
teste.head()

,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,dload,...,state_CON,state_ECO,state_FIN,state_INT,state_PAR,state_REQ,state_RST,state_URN,state_no,label
0,0.121478,6,4,258,172,74.087490,252,254,14158.942380,8495.365234,...,False,False,True,False,False,False,False,False,False,0
1,0.649902,14,38,734,42014,78.473372,62,252,8395.112305,503571.312500,...,False,False,True,False,False,False,False,False,False,0
2,1.623129,8,16,364,13186,14.170161,62,252,1572.271851,60929.230470,...,False,False,True,False,False,False,False,False,False,0
3,1.681642,12,12,628,770,13.677108,62,252,2740.178955,3358.622070,...,False,False,True,False,False,False,False,False,False,0
4,0.449454,10,6,534,268,33.373826,254,252,8561.499023,3987.059814,...,False,False,True,False,False,False,False,False,False,0

In [14]:
teste = teste.drop(columns=['label'])

In [15]:
amostra = teste.sample(n=1)

In [16]:
amostra.head()

,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,dload,...,service_ssl,state_CON,state_ECO,state_FIN,state_INT,state_PAR,state_REQ,state_RST,state_URN,state_no
109831,0.000004,2,0,200,0,250000.0006,254,0,200000000.0,0.0,...,False,False,False,False,True,False,False,False,False,False

In [17]:
modelo1.predict_proba(amostra)

array([[0., 1.]])

In [18]:
import joblib

# Salvar o modelo em um arquivo
joblib.dump(modelo1, 'RandomForest.pkl')

['RandomForest.pkl']

In [19]:
modelo2 = melhores_modelos[1]

In [20]:
print(modelo2)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=6698, verbose=0,
                     warm_start=False)

In [21]:
evaluate_model(modelo2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [22]:
modelo2.predict_proba(amostra)

array([[0., 1.]])

In [23]:
import joblib

# Salvar o modelo em um arquivo
joblib.dump(modelo2, 'ExtraTrees.pkl')

['Extratee.pkl']

In [24]:
modelo3 = melhores_modelos[2]

In [25]:
print(modelo3)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=6698, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [26]:
evaluate_model(modelo3)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [27]:
import joblib

# Salvar o modelo em um arquivo
joblib.dump(modelo3, 'XGBoost.pkl')

['XGBoost.pkl']

In [28]:
print('versao', joblib.__version__)

versao 1.2.0